### ISSUE TITLE
ThinkPHP 框架的引导文件 base.php 不存在

### ISSUE THREAD

**Issue by cro3odile** [HuaQiPro/Superplayer#1]
Warning: require(/www/wwwroot/Superplayer-1.4.5/public\..\thinkphp\base.php): failed to open stream: No such file or directory in /www/wwwroot/Superplayer-1.4.5/public/install.php on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/Superplayer-1.4.5/public\..\thinkphp\base.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/Superplayer-1.4.5/public/install.php on line 18

**Comment by Cro3odile** [comment]
> Warning: require(/www/wwwroot/Superplayer-1.4.5/public..\thinkphp\base.php): failed to open stream: No such file or directory in /www/wwwroot/Superplayer-1.4.5/public/install.php on line 18
> 
> Fatal error: require(): Failed opening required '/www/wwwroot/Superplayer-1.4.5/public..\thinkphp\base.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/Superplayer-1.4.5/public/install.php on line 18
